apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: {{ .Values.namespace }}
data:
  REDIS_HOST: {{ .Values.configMap.REDIS_HOST | quote }}
  CATALOGUE_HOST: {{ .Values.configMap.CATALOGUE_HOST | quote }}
  CATALOGUE_PORT: {{ .Values.configMap.CATALOGUE_PORT | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deploy
  namespace: {{ .Values.namespace }}
  # these are deployment labels
  labels:
    project: roboshop
    component: cart
    tier: backend
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    # Deployment manages pods with this label
    matchLabels:
      project: roboshop
      component: cart
      tier: backend
  # pod definition
  template:
    metadata:
      labels:  # <-- Pod label; Service will use this
        project: roboshop
        component: cart
        tier: backend
    spec:
      containers:
      - name: cart
        image: "{{ .Values.deployment.imageRepo }}:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        envFrom:
        - configMapRef:
            name: cart-config
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
        readinessProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 1
          periodSeconds: 15
        resources:
          requests:
            cpu: "100M"
            memory: "128Mi"
          limits:
            cpu: "200M"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    project: roboshop
    component: cart
    tier: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.targetPort }}
