FROM node:20.19.5-alpine3.22 AS build
WORKDIR /opt/server
COPY package*.json .
RUN npm install
COPY . .

FROM node:20.19.5-alpine3.22
WORKDIR /opt/server
RUN addgroup -S appgroup && \
    useradd -S appuser -G appgroup && \
    chown -R appuser:appgroup /opt/server
COPY --from=build /opt/server .
USER appuser
EXPOSE 8080
ENV MONGO="true" \
  MONGO_URL="mongodb://mongodb:27017/catalogue"
CMD ["node","server.js"]