apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
  namespace: {{ .Values.namespace }}
data:
  MONGO: {{ .Values.config.MONGO | quote}}
  MONGO_URL: {{ .Values.config.MONGO_URL | quote}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-deploy
  namespace: {{ .Values.namespace }}
  labels:
    project: roboshop
    component: catalogue
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: catalogue
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        component: catalogue
        tier: backend
    spec:
      containers:
        - name: catalogue-container
          image: joindevops/catalogue:v1
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: catalogue-config-map
          ports:
          - name: http
            containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 3
            periodSeconds: 10
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 3
            periodSeconds: 10
            initialDelaySeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    project: roboshop
    component: catalogue
    tier: backend
  ports:
    - protocol: TCP
      port: 8080       # svc Port
      targetPort: 8080 # container port